# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d55e73b24f1f5aceeb012e58bc6d5f6"
name = "Airventory Product"
handle = "airventory-product"
application_url = "https://witty-werewolf-positively.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://witty-werewolf-positively.ngrok-free.app/auth/callback",
  "https://airventory.io/auth/callback"
]

[pos]
embedded = false

[app_preferences]
url = "https://airventory.io/preferences"
